service: slot-n-slot-lambda
provider:
  name: aws
  runtime: nodejs6.10
  environment: ${file(./env/${opt:stage}.yml)}
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:*"
     Resource: "arn:aws:s3:::slot-n-slot-home/*"
   - Effect: Allow
     Action:
       - 'cloudwatch:PutMetricData'
     Resource: '*'

package:
  artifact: dst.zip

functions:
  slotFrontendRender:
    handler: handlers.frontRender
    timeout: 10
    events:
      - http:
          path: frontRender
          method: get
      - http:
          path: frontRender/{proxy+}
          method: any

  subscribeMailingList:
    handler: handlers.subscribeMailingList
    timeout: 10
    events:
      - http:
          path: subscribeMailingList
          method: post
          cors: true

resources:
  Resources:
    SlotFrontendRenderLogGroup:
      Properties:
        RetentionInDays: "30"

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          ViewerCertificate:
            AcmCertificateArn: arn:aws:acm:us-east-1:966390130392:certificate/b81df856-c668-4b50-a8a9-f4a506ae2e3e
          DefaultRootObject: ''
          Enabled: true
          DefaultCacheBehavior:
            DefaultTTL: 300
            MaxTTL: 300
            MinTTL: 300
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - HEAD
              - GET
            ForwardedValues:
              QueryString: true
              Headers:
                - original-uri
                - User-Agent
                - X-Forwarded-For
            TargetOriginId: "${self:service}-${opt:stage}-api-gateway"
            ViewerProtocolPolicy: redirect-to-https
          Aliases:
            - ${file(./env/${opt:stage}.yml):DNS_ALIAS1}
            - ${file(./env/${opt:stage}.yml):DNS_ALIAS2}
          Origins:
          - CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
            DomainName:
              "Fn::Join": ["", [{"Ref": "ApiGatewayRestApi"}, ".execute-api.${self:provider.region}.amazonaws.com"]]
            Id: "${self:service}-${opt:stage}-api-gateway"
            OriginPath: /${opt:stage}/frontRender
